version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.production
    restart: unless-stopped
      